import spacy
from spacy.matcher import PhraseMatcher
from rapidfuzz import fuzz
import re

nlp = spacy.load("en_core_web_sm")

# USED AI TO CREATE TABLE OF MOST COMMON SOFTWARE SKILLS AND SIMILAR SPELLINGS
SKILLS = {
    "Python": ["python", "py"],
    "Java": ["java"],
    "C++": ["c++", "cpp"],
    "C#": ["c#", "c-sharp"],
    "SQL": ["sql", "postgres", "postgresql", "mysql", "mssql", "sqlite"],
    "JavaScript": ["javascript", "js"],
    "TypeScript": ["typescript", "ts"],
    "Go": ["go", "golang"],
    "Ruby": ["ruby", "rb"],
    "PHP": ["php"],
    "React": ["react", "react.js"],
    "Angular": ["angular", "angular.js"],
    "Vue.js": ["vue", "vue.js"],
    "Svelte": ["svelte"],
    "Node.js": ["node.js", "node js", "node"],
    "Express": ["express", "express.js", "expressjs"],
    "Django": ["django", "dj"],
    "Flask": ["flask"],
    "Docker": ["docker"],
    "Kubernetes": ["k8s", "kubernetes"],
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure", "microsoft azure"],
    "GCP": ["gcp", "google cloud", "google cloud platform"],
    "Terraform": ["terraform"],
    "Jenkins": ["jenkins"],
    "GitLab CI": ["gitlab ci", "gitlab"],
    "CircleCI": ["circleci"],
    "Git": ["git", "github", "gitlab", "bitbucket"],
    "Linux": ["linux", "ubuntu", "debian", "centos", "fedora"],
    "MongoDB": ["mongodb", "mongo"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MySQL": ["mysql"],
    "Redis": ["redis"],
    "Elasticsearch": ["elasticsearch", "es"],
    "TensorFlow": ["tensorflow", "tf"],
    "PyTorch": ["pytorch", "torch"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "Keras": ["keras"],
    "XGBoost": ["xgboost"],
    "LightGBM": ["lightgbm"],
    "OpenCV": ["opencv", "cv2"],
    "Spark": ["spark", "pyspark"],
    "Hadoop": ["hadoop"],
    "Kafka": ["kafka"],
    "NumPy": ["numpy", "np"],
    "Pandas": ["pandas", "pd"],
    "Matplotlib": ["matplotlib", "plt"],
    "Seaborn": ["seaborn", "sns"],
    "Plotly": ["plotly"],
    "BeautifulSoup": ["beautifulsoup", "bs4"],
    "Selenium": ["selenium"],
# Languages
    "Rust": ["rust", "rs"],
    "Swift": ["swift"],
    "Kotlin": ["kotlin", "kt"],
    "Scala": ["scala"],
    "R": ["r language", "r programming"],
    "MATLAB": ["matlab"],
    "Perl": ["perl", "pl"],
    "Haskell": ["haskell", "hs"],
    "Elixir": ["elixir", "ex"],
    "Erlang": ["erlang"],
    "Clojure": ["clojure", "clj"],
    "F#": ["f#", "fsharp"],
    "Dart": ["dart"],
    "Julia": ["julia"],
    "Lua": ["lua"],
    "Groovy": ["groovy"],
    "Assembly": ["assembly", "asm"],
    "COBOL": ["cobol"],
    "Fortran": ["fortran"],
    "Prolog": ["prolog"],
    "Lisp": ["lisp", "common lisp"],
    "Scheme": ["scheme"],
    "Racket": ["racket"],
    "OCaml": ["ocaml"],
    "Nim": ["nim"],
    "Crystal": ["crystal"],
    "Zig": ["zig"],
    "V": ["v language", "vlang"],
    "Solidity": ["solidity", "sol"],
    "WebAssembly": ["webassembly", "wasm"],
    "VHDL": ["vhdl"],
    "Verilog": ["verilog"],
    "PowerShell": ["powershell", "ps1"],
    "Bash": ["bash", "shell", "sh"],
    "Zsh": ["zsh"],
    "AWK": ["awk"],
    "Sed": ["sed"],
    "Tcl": ["tcl"],
    "Ada": ["ada"],
    "D": ["d language", "dlang"],

    # Frontend Frameworks & Libraries
    "Next.js": ["next.js", "nextjs", "next"],
    "Nuxt.js": ["nuxt.js", "nuxtjs", "nuxt"],
    "Gatsby": ["gatsby", "gatsbyjs"],
    "Remix": ["remix", "remix.run"],
    "Astro": ["astro"],
    "SvelteKit": ["sveltekit"],
    "Solid.js": ["solid.js", "solidjs", "solid"],
    "Qwik": ["qwik"],
    "Ember.js": ["ember", "ember.js", "emberjs"],
    "Backbone.js": ["backbone", "backbone.js"],
    "Alpine.js": ["alpine", "alpine.js", "alpinejs"],
    "Lit": ["lit", "lit-element"],
    "Preact": ["preact"],
    "Inferno": ["inferno"],
    "Mithril": ["mithril"],
    "Stimulus": ["stimulus", "stimulusjs"],
    "HTMX": ["htmx"],
    "jQuery": ["jquery"],

    # CSS Frameworks & Styling
    "Tailwind CSS": ["tailwind", "tailwindcss", "tailwind css"],
    "Bootstrap": ["bootstrap"],
    "Material UI": ["material ui", "mui", "material-ui"],
    "Chakra UI": ["chakra ui", "chakra"],
    "Ant Design": ["ant design", "antd"],
    "Shadcn UI": ["shadcn", "shadcn ui"],
    "Radix UI": ["radix", "radix ui"],
    "Styled Components": ["styled-components", "styled components"],
    "Emotion": ["emotion", "css-in-js"],
    "Sass": ["sass", "scss"],
    "Less": ["less", "lesscss"],
    "PostCSS": ["postcss"],
    "CSS Modules": ["css modules"],
    "Bulma": ["bulma"],
    "Foundation": ["foundation css"],
    "Semantic UI": ["semantic ui", "fomantic"],
    "Headless UI": ["headless ui", "headlessui"],
    "DaisyUI": ["daisyui", "daisy ui"],
    "PrimeReact": ["primereact", "primevue", "primefaces"],

    # Backend Frameworks
    "FastAPI": ["fastapi", "fast api"],
    "Spring Boot": ["spring boot", "spring", "springboot"],
    "Laravel": ["laravel"],
    "Symfony": ["symfony"],
    "Ruby on Rails": ["rails", "ruby on rails", "ror"],
    "NestJS": ["nestjs", "nest.js", "nest"],
    "Fastify": ["fastify"],
    "Hapi": ["hapi", "hapi.js"],
    "Koa": ["koa", "koa.js"],
    "Gin": ["gin", "gin-gonic"],
    "Echo": ["echo framework"],
    "Fiber": ["fiber", "gofiber"],
    "Actix": ["actix", "actix-web"],
    "Rocket": ["rocket", "rocket.rs"],
    "Axum": ["axum"],
    "Phoenix": ["phoenix", "phoenix framework"],
    "ASP.NET": ["asp.net", "aspnet", "asp.net core"],
    "Ktor": ["ktor"],
    "Micronaut": ["micronaut"],
    "Quarkus": ["quarkus"],
    "Play Framework": ["play framework", "playframework"],
    "Sinatra": ["sinatra"],
    "Tornado": ["tornado"],
    "Sanic": ["sanic"],
    "Lumen": ["lumen"],
    "CodeIgniter": ["codeigniter"],
    "CakePHP": ["cakephp"],
    "Yii": ["yii", "yii2"],
    "Grails": ["grails"],
    "Strapi": ["strapi"],
    "Directus": ["directus"],

    # Databases
    "DynamoDB": ["dynamodb", "dynamo"],
    "Cassandra": ["cassandra", "apache cassandra"],
    "CouchDB": ["couchdb", "couch"],
    "Neo4j": ["neo4j", "graph database"],
    "InfluxDB": ["influxdb", "influx"],
    "TimescaleDB": ["timescaledb", "timescale"],
    "CockroachDB": ["cockroachdb", "cockroach"],
    "MariaDB": ["mariadb"],
    "Oracle": ["oracle", "oracle db", "oracle database"],
    "SQLite": ["sqlite"],
    "Firestore": ["firestore", "firebase firestore"],
    "Supabase": ["supabase"],
    "PlanetScale": ["planetscale"],
    "Fauna": ["fauna", "faunadb"],
    "RethinkDB": ["rethinkdb"],
    "ArangoDB": ["arangodb"],
    "Couchbase": ["couchbase"],
    "RavenDB": ["ravendb"],
    "HBase": ["hbase"],
    "Snowflake": ["snowflake"],
    "BigQuery": ["bigquery", "big query"],
    "Redshift": ["redshift", "amazon redshift"],
    "Databricks": ["databricks"],
    "ClickHouse": ["clickhouse"],
    "Druid": ["druid", "apache druid"],
    "Pinot": ["pinot", "apache pinot"],
    "Dask": ["dask"],
    "DuckDB": ["duckdb"],
    "Turso": ["turso"],
    "Neon": ["neon", "neondb"],
    "Xata": ["xata"],
    "SingleStore": ["singlestore", "memsql"],
    "VoltDB": ["voltdb"],
    "TiDB": ["tidb"],
    "YugabyteDB": ["yugabyte", "yugabytedb"],

    # Cloud & Infrastructure
    "Heroku": ["heroku"],
    "Vercel": ["vercel"],
    "Netlify": ["netlify"],
    "DigitalOcean": ["digitalocean", "digital ocean", "do"],
    "Linode": ["linode", "akamai cloud"],
    "Cloudflare": ["cloudflare", "cf"],
    "Fly.io": ["fly.io", "flyio"],
    "Railway": ["railway"],
    "Render": ["render"],
    "AWS Lambda": ["lambda", "aws lambda", "serverless functions"],
    "AWS EC2": ["ec2", "aws ec2"],
    "AWS S3": ["s3", "aws s3"],
    "AWS RDS": ["rds", "aws rds"],
    "AWS ECS": ["ecs", "aws ecs"],
    "AWS EKS": ["eks", "aws eks"],
    "AWS CloudFront": ["cloudfront", "aws cloudfront"],
    "AWS SQS": ["sqs", "aws sqs"],
    "AWS SNS": ["sns", "aws sns"],
    "Azure Functions": ["azure functions"],
    "Azure DevOps": ["azure devops", "ado"],
    "Google Cloud Run": ["cloud run", "google cloud run"],
    "Google Cloud Functions": ["cloud functions"],
    "Firebase": ["firebase"],
    "Pulumi": ["pulumi"],
    "Ansible": ["ansible"],
    "Chef": ["chef"],
    "Puppet": ["puppet"],
    "Vagrant": ["vagrant"],
    "Packer": ["packer"],
    "Consul": ["consul"],
    "Vault": ["vault", "hashicorp vault"],
    "Nomad": ["nomad", "hashicorp nomad"],
    "OpenStack": ["openstack"],
    "VMware": ["vmware", "vsphere"],
    "Proxmox": ["proxmox"],

    # DevOps & CI/CD
    "GitHub Actions": ["github actions", "gh actions"],
    "Travis CI": ["travis ci", "travis"],
    "Bamboo": ["bamboo", "atlassian bamboo"],
    "TeamCity": ["teamcity"],
    "Argo CD": ["argocd", "argo cd", "argo"],
    "Flux": ["flux", "fluxcd"],
    "Spinnaker": ["spinnaker"],
    "Drone CI": ["drone", "drone ci"],
    "Buildkite": ["buildkite"],
    "Concourse": ["concourse", "concourse ci"],
    "Tekton": ["tekton"],
    "Helm": ["helm", "helm charts"],
    "Kustomize": ["kustomize"],
    "Istio": ["istio"],
    "Linkerd": ["linkerd"],
    "Envoy": ["envoy", "envoy proxy"],
    "Nginx": ["nginx"],
    "Apache": ["apache", "apache httpd"],
    "HAProxy": ["haproxy"],
    "Traefik": ["traefik"],
    "Caddy": ["caddy", "caddyserver"],
    "Prometheus": ["prometheus"],
    "Grafana": ["grafana"],
    "Datadog": ["datadog"],
    "New Relic": ["new relic", "newrelic"],
    "Splunk": ["splunk"],
    "ELK Stack": ["elk", "elk stack", "elastic stack"],
    "Logstash": ["logstash"],
    "Kibana": ["kibana"],
    "Fluentd": ["fluentd"],
    "Jaeger": ["jaeger"],
    "Zipkin": ["zipkin"],
    "OpenTelemetry": ["opentelemetry", "otel"],
    "Sentry": ["sentry"],
    "PagerDuty": ["pagerduty"],
    "OpsGenie": ["opsgenie"],

    # Testing
    "Jest": ["jest"],
    "Pytest": ["pytest"],
    "Mocha": ["mocha", "mocha.js"],
    "Jasmine": ["jasmine"],
    "Cypress": ["cypress"],
    "Playwright": ["playwright"],
    "Puppeteer": ["puppeteer"],
    "TestNG": ["testng"],
    "JUnit": ["junit", "junit5"],
    "RSpec": ["rspec"],
    "PHPUnit": ["phpunit"],
    "Vitest": ["vitest"],
    "Testing Library": ["testing library", "react testing library"],
    "Enzyme": ["enzyme"],
    "Storybook": ["storybook"],
    "Cucumber": ["cucumber", "bdd"],
    "k6": ["k6", "load testing"],
    "Locust": ["locust"],
    "Gatling": ["gatling"],
    "JMeter": ["jmeter", "apache jmeter"],
    "Postman": ["postman"],
    "Insomnia": ["insomnia"],
    "SoapUI": ["soapui"],
    "Appium": ["appium"],
    "Detox": ["detox"],
    "XCTest": ["xctest"],
    "Espresso": ["espresso", "android espresso"],

    # Mobile Development
    "React Native": ["react native", "rn"],
    "Flutter": ["flutter"],
    "Ionic": ["ionic"],
    "Xamarin": ["xamarin"],
    "SwiftUI": ["swiftui"],
    "UIKit": ["uikit"],
    "Jetpack Compose": ["jetpack compose", "compose"],
    "Android SDK": ["android sdk", "android development"],
    "iOS SDK": ["ios sdk", "ios development"],
    "Expo": ["expo"],
    "Capacitor": ["capacitor"],
    "Cordova": ["cordova", "phonegap"],

    # Data Science & ML
    "Hugging Face": ["hugging face", "huggingface", "transformers"],
    "LangChain": ["langchain", "lang chain"],
    "LlamaIndex": ["llamaindex", "llama index", "gpt index"],
    "Ollama": ["ollama"],
    "ONNX": ["onnx"],
    "MLflow": ["mlflow"],
    "Weights & Biases": ["wandb", "weights and biases", "weights & biases"],
    "DVC": ["dvc", "data version control"],
    "Airflow": ["airflow", "apache airflow"],
    "Prefect": ["prefect"],
    "Dagster": ["dagster"],
    "Metaflow": ["metaflow"],
    "Ray": ["ray", "ray.io"],
    "Dask ML": ["dask-ml"],
    "CatBoost": ["catboost"],
    "spaCy": ["spacy"],
    "NLTK": ["nltk"],
    "Gensim": ["gensim"],
    "FastText": ["fasttext"],
    "Stable Diffusion": ["stable diffusion"],
    "OpenAI API": ["openai", "openai api", "gpt api"],
    "Anthropic API": ["anthropic api", "claude api"],
    "Cohere": ["cohere"],
    "Pinecone": ["pinecone"],
    "Weaviate": ["weaviate"],
    "Chroma": ["chroma", "chromadb"],
    "Qdrant": ["qdrant"],
    "Milvus": ["milvus"],
    "JAX": ["jax"],
    "Flax": ["flax"],
    "MXNet": ["mxnet"],
    "Caffe": ["caffe"],
    "Theano": ["theano"],
    "Rapids": ["rapids", "cuml", "cudf"],
    "Prophet": ["prophet", "facebook prophet"],
    "Statsmodels": ["statsmodels"],
    "SciPy": ["scipy"],
    "Sympy": ["sympy"],
    "NetworkX": ["networkx"],
    "Optuna": ["optuna"],
    "Hyperopt": ["hyperopt"],
    "SHAP": ["shap"],
    "LIME": ["lime"],
    "Evidently": ["evidently", "evidently ai"],
    "Great Expectations": ["great expectations"],
    "Feast": ["feast", "feature store"],
    "Tecton": ["tecton"],
    "BentoML": ["bentoml"],
    "Seldon": ["seldon"],
    "KServe": ["kserve"],
    "TorchServe": ["torchserve"],
    "Triton": ["triton", "nvidia triton"],

    # Data Engineering
    "dbt": ["dbt", "data build tool"],
    "Fivetran": ["fivetran"],
    "Airbyte": ["airbyte"],
    "Stitch": ["stitch", "stitch data"],
    "Talend": ["talend"],
    "Informatica": ["informatica"],
    "Apache Beam": ["apache beam", "beam"],
    "Flink": ["flink", "apache flink"],
    "Storm": ["storm", "apache storm"],
    "Samza": ["samza", "apache samza"],
    "Pulsar": ["pulsar", "apache pulsar"],
    "RabbitMQ": ["rabbitmq"],
    "ActiveMQ": ["activemq"],
    "NATS": ["nats"],
    "ZeroMQ": ["zeromq", "zmq"],
    "Kinesis": ["kinesis", "aws kinesis"],
    "EventBridge": ["eventbridge"],
    "Apache Hive": ["hive", "apache hive"],
    "Presto": ["presto", "trino"],
    "Pig": ["pig", "apache pig"],
    "Sqoop": ["sqoop", "apache sqoop"],
    "Flume": ["flume", "apache flume"],
    "NiFi": ["nifi", "apache nifi"],
    "Superset": ["superset", "apache superset"],

    # API & Integration
    "GraphQL": ["graphql"],
    "REST API": ["rest", "rest api", "restful"],
    "gRPC": ["grpc"],
    "WebSockets": ["websockets", "websocket", "ws"],
    "OpenAPI": ["openapi", "swagger"],
    "tRPC": ["trpc"],
    "Apollo": ["apollo", "apollo graphql"],
    "Hasura": ["hasura"],
    "Kong": ["kong", "kong gateway"],
    "AWS API Gateway": ["api gateway", "aws api gateway"],
    "MuleSoft": ["mulesoft"],
    "Apigee": ["apigee"],
    "Zapier": ["zapier"],
    "Make": ["make", "integromat"],

    # Security
    "OAuth": ["oauth", "oauth2"],
    "JWT": ["jwt", "json web token"],
    "SAML": ["saml"],
    "LDAP": ["ldap"],
    "Keycloak": ["keycloak"],
    "Auth0": ["auth0"],
    "Okta": ["okta"],
    "OpenID Connect": ["openid", "oidc", "openid connect"],
    "SSL/TLS": ["ssl", "tls", "ssl/tls"],
    "Vault Secrets": ["secrets management"],
    "Snyk": ["snyk"],
    "SonarQube": ["sonarqube", "sonar"],
    "OWASP": ["owasp"],
    "Burp Suite": ["burp suite", "burp"],
    "Metasploit": ["metasploit"],
    "Wireshark": ["wireshark"],
    "Nmap": ["nmap"],
    "Nessus": ["nessus"],

    # Version Control & Collaboration
    "Jira": ["jira"],
    "Confluence": ["confluence"],
    "Notion": ["notion"],
    "Linear": ["linear"],
    "Trello": ["trello"],
    "Asana": ["asana"],
    "Monday.com": ["monday", "monday.com"],
    "Slack": ["slack"],
    "Microsoft Teams": ["microsoft teams", "ms teams"],
    "Figma": ["figma"],
    "Zeplin": ["zeplin"],
    "Sketch": ["sketch"],
    "InVision": ["invision"],
    "Miro": ["miro"],
    "LucidChart": ["lucidchart"],

    # Game Development
    "Unity": ["unity", "unity3d"],
    "Unreal Engine": ["unreal", "unreal engine", "ue5", "ue4"],
    "Godot": ["godot"],
    "Pygame": ["pygame"],
    "LibGDX": ["libgdx"],
    "Phaser": ["phaser", "phaser.js"],
    "Three.js": ["three.js", "threejs"],
    "Babylon.js": ["babylon.js", "babylonjs"],
    "WebGL": ["webgl"],
    "OpenGL": ["opengl"],
    "Vulkan": ["vulkan"],
    "DirectX": ["directx"],
    "Metal": ["metal", "apple metal"],

    # Embedded & Systems
    "Arduino": ["arduino"],
    "Raspberry Pi": ["raspberry pi", "raspi", "rpi"],
    "RTOS": ["rtos", "freertos"],
    "Embedded C": ["embedded c", "embedded systems"],
    "FPGA": ["fpga"],
    "ROS": ["ros", "robot operating system"],
    "PLC": ["plc", "programmable logic controller"],
    "LabVIEW": ["labview"],
    "MicroPython": ["micropython"],
    "Zephyr": ["zephyr", "zephyr rtos"],

    # Blockchain & Web3
    "Ethereum": ["ethereum", "eth"],
    "Bitcoin": ["bitcoin", "btc"],
    "Web3.js": ["web3.js", "web3"],
    "Ethers.js": ["ethers.js", "ethers"],
    "Hardhat": ["hardhat"],
    "Truffle": ["truffle"],
    "Foundry": ["foundry"],
    "IPFS": ["ipfs"],
    "Chainlink": ["chainlink"],
    "OpenZeppelin": ["openzeppelin"],
    "Polygon": ["polygon", "matic"],
    "Solana": ["solana", "sol"],
    "Substrate": ["substrate", "polkadot"],

    # Desktop Development
    "Electron": ["electron", "electron.js"],
    "Tauri": ["tauri"],
    "Qt": ["qt", "pyqt", "pyside"],
    "GTK": ["gtk", "gtk+"],
    "wxWidgets": ["wxwidgets", "wx"],
    "WPF": ["wpf", "windows presentation foundation"],
    "WinForms": ["winforms", "windows forms"],
    "MAUI": ["maui", ".net maui"],
    "JavaFX": ["javafx"],
    "Swing": ["swing", "java swing"],
    "Tkinter": ["tkinter"],
    "PyQt": ["pyqt", "pyqt5", "pyqt6"],

    # Scientific Computing & Visualization
    "D3.js": ["d3", "d3.js"],
    "Vega": ["vega", "vega-lite"],
    "Bokeh": ["bokeh"],
    "Altair": ["altair"],
    "ggplot2": ["ggplot2", "ggplot"],
    "Shiny": ["shiny", "r shiny"],
    "Dash": ["dash", "plotly dash"],
    "Streamlit": ["streamlit"],
    "Gradio": ["gradio"],
    "Panel": ["panel", "holoviz"],
    "Folium": ["folium"],
    "Geopandas": ["geopandas"],
    "Shapely": ["shapely"],
    "GDAL": ["gdal"],
    "ArcGIS": ["arcgis"],
    "QGIS": ["qgis"],

    # Build Tools & Package Managers
    "Webpack": ["webpack"],
    "Vite": ["vite"],
    "Rollup": ["rollup", "rollup.js"],
    "Parcel": ["parcel"],
    "esbuild": ["esbuild"],
    "Turbopack": ["turbopack"],
    "Babel": ["babel"],
    "SWC": ["swc"],
    "npm": ["npm"],
    "Yarn": ["yarn"],
    "pnpm": ["pnpm"],
    "Bun": ["bun"],
    "Maven": ["maven", "apache maven"],
    "Gradle": ["gradle"],
    "Ant": ["ant", "apache ant"],
    "Makefile": ["makefile", "make"],
    "CMake": ["cmake"],
    "Bazel": ["bazel"],
    "Nx": ["nx", "nrwl"],
    "Turborepo": ["turborepo"],
    "Lerna": ["lerna"],
    "pip": ["pip", "pypi"],
    "Poetry": ["poetry"],
    "Conda": ["conda", "anaconda", "miniconda"],
    "Cargo": ["cargo"],
    "Composer": ["composer"],
    "Bundler": ["bundler", "gem"],
    "Go Modules": ["go modules", "go mod"],

    # Editors & IDEs
    "VS Code": ["vscode", "vs code", "visual studio code"],
    "IntelliJ IDEA": ["intellij", "intellij idea"],
    "PyCharm": ["pycharm"],
    "WebStorm": ["webstorm"],
    "Vim": ["vim", "neovim", "nvim"],
    "Emacs": ["emacs"],
    "Sublime Text": ["sublime", "sublime text"],
    "Xcode": ["xcode"],
    "Android Studio": ["android studio"],
    "Eclipse": ["eclipse"],
    "NetBeans": ["netbeans"],
    "Visual Studio": ["visual studio", "vs"],

    # Misc & Emerging Tech
    "WebRTC": ["webrtc"],
    "Socket.IO": ["socket.io", "socketio"],
    "PWA": ["pwa", "progressive web app"],
    "Service Workers": ["service workers"],
    "IndexedDB": ["indexeddb"],
    "Web Components": ["web components"],
    "WASM": ["wasm", "webassembly"],
    "Edge Computing": ["edge computing"],
    "Serverless": ["serverless", "serverless framework"],
    "Micro Frontends": ["micro frontends", "microfrontends"],
    "Microservices": ["microservices"],
    "Event Sourcing": ["event sourcing"],
    "CQRS": ["cqrs"],
    "GraphDB": ["graphdb"],
    "Vector DB": ["vector database", "vectordb"],
    "LLM": ["llm", "large language model"],
    "RAG": ["rag", "retrieval augmented generation"],
    "Computer Vision": ["computer vision", "cv"],
    "NLP": ["nlp", "natural language processing"],
    "Reinforcement Learning": ["reinforcement learning", "rl"],
    "MLOps": ["mlops"],
    "DataOps": ["dataops"],
    "FinOps": ["finops"],
    "GitOps": ["gitops"],
    "SRE": ["sre", "site reliability engineering"],
    "Chaos Engineering": ["chaos engineering", "chaos monkey"],
    "Feature Flags": ["feature flags", "feature toggles", "launchdarkly"],
    "A/B Testing": ["a/b testing", "ab testing", "split testing"],
    "CDN": ["cdn", "content delivery network"],
    "DNS": ["dns"],
    "Load Balancing": ["load balancing", "load balancer"],
    "Service Mesh": ["service mesh"],
    "API Design": ["api design"],
    "System Design": ["system design"],
    "Design Patterns": ["design patterns"],
    "DDD": ["ddd", "domain driven design"],
    "TDD": ["tdd", "test driven development"],
    "BDD": ["bdd", "behavior driven development"],
    "Agile": ["agile", "scrum", "kanban"],
    "CI/CD": ["ci/cd", "cicd", "continuous integration", "continuous deployment"],
    "DevSecOps": ["devsecops"],
    "Pair Programming": ["pair programming"],
    "Code Review": ["code review"],
    "Technical Writing": ["technical writing", "documentation"],
    "Markdown": ["markdown", "md"],
    "LaTeX": ["latex"],
    "Jupyter": ["jupyter", "jupyter notebook", "ipynb"],
    "Colab": ["colab", "google colab"],
    "Databricks Notebooks": ["databricks notebooks"],
    "Observable": ["observable", "observablehq"],
}

ROLES = [
    "backend developer",
    "frontend developer",
    "software engineer",
    "data scientist",
    "data analyst",
]

matcher = PhraseMatcher(nlp.vocab, attr="LOWER") # AI USED WHEN I GOT STUCK READING SPACY DOCUMENTATION
for skill_name, aliases in SKILLS.items():
    patterns = [nlp.make_doc(alias) for alias in aliases]
    matcher.add(skill_name, patterns)

def extract_skills(text: str, fuzzy_threshold: int = 85):
    doc = nlp(text)
    matches = matcher(doc)
    found_skills = set()

    # 1. Exact Matching
    for match_id, start, end in matches:
        skill_name = nlp.vocab.strings[match_id]
        found_skills.add(skill_name) 

    text_lower = text.lower()
    words = re.findall(r'\b[a-z0-9+#.]+\b', text_lower) #USED AI TO SEPERATE INDIVIDUAL WORDS WITH CONFUSING REGEX

    # 2. Fuzzy Matching
    for skill, aliases in SKILLS.items():
        if skill in found_skills:
            continue
            
        for alias in aliases:
            alias_low = alias.lower()
            if " " in alias_low:
                if fuzz.partial_ratio(alias_low, text_lower) >= fuzzy_threshold:
                    found_skills.add(skill)
                    break 
            else:
                for word in words:
                    if fuzz.ratio(alias_low, word) >= fuzzy_threshold:
                        found_skills.add(skill)
                        break 

    return list(found_skills)

def detect_role(text: str):
    text_lower = text.lower()

    for role in ROLES:
        if role in text_lower:
            return role

    try:
        start_marker = "position: "
        end_marker = "co-op work term posted:"
        
        start_idx = text_lower.index(start_marker) + len(start_marker)
        end_idx = text_lower.index(end_marker)
        
        return text[start_idx:end_idx].strip()
    except ValueError:
        return "Unknown Role"